services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -cors * -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  postgres:
    image: postgres:15-alpine
    container_name: tip-manager-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tip_manager}
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
